# Generated by Django 5.1.4 on 2024-12-17 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('MobileNet_SSD', 'MobileNetSSD')], verbose_name='Используемая модель')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('source_object', models.ImageField(upload_to='source_objects/', verbose_name='Исходный объект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ('-pub_date',),
            },
        ),
    ]
