# Generated by Django 5.1.4 on 2024-12-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='source_object',
        ),
        migrations.AddField(
            model_name='object',
            name='processed_image',
            field=models.ImageField(default=1, upload_to='processed_images/', verbose_name='Распознанное изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='source_image',
            field=models.ImageField(default=1, upload_to='original_images/', verbose_name='Исходное изображение'),
            preserve_default=False,
        ),
    ]
