# Generated by Django 5.1.4 on 2024-12-18 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0002_remove_object_source_object_object_processed_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=100, verbose_name='Тип изображения')),
                ('confidence', models.FloatField(verbose_name='Уверенность')),
                ('location', models.CharField(max_length=255)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_objects', to='object_detection.object', verbose_name='Оригинальное изображение')),
            ],
            options={
                'verbose_name': 'Распознанный объект',
                'verbose_name_plural': 'Распознанные объекты',
            },
        ),
    ]
