# Generated by Django 5.1.4 on 2024-12-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0003_detectedobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedobject',
            name='model',
            field=models.CharField(choices=[('MobileNet_SSD', 'MobileNetSSD')], default=1, verbose_name='Используемая модель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detectedobject',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Координаты'),
        ),
    ]
